# Generated by Django 2.2 on 2020-01-31 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrd', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='academicsmast',
            name='emp_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='academicsmast',
            name='document',
            field=models.ImageField(null=True, upload_to='images/acedmic'),
        ),
        migrations.AlterField(
            model_name='bankdetails',
            name='document',
            field=models.ImageField(null=True, upload_to='images/bankdoc'),
        ),
        migrations.AlterField(
            model_name='document',
            name='files',
            field=models.ImageField(null=True, upload_to='images/otherdocs'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='emp_img',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
    ]
