# Generated by Django 2.2 on 2020-01-31 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrd', '0002_auto_20200131_1538'),
    ]

    operations = [
        migrations.AlterField(
            model_name='academicsmast',
            name='document',
            field=models.FileField(null=True, upload_to='acedmic/'),
        ),
        migrations.AlterField(
            model_name='bankdetails',
            name='document',
            field=models.FileField(null=True, upload_to='bankdoc/'),
        ),
        migrations.AlterField(
            model_name='document',
            name='files',
            field=models.FileField(null=True, upload_to='otherdocs/'),
        ),
    ]
