# Generated by Django 2.2 on 2020-02-01 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrd', '0003_auto_20200131_1651'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankdetails',
            name='document',
            field=models.ImageField(null=True, upload_to='bankdoc/'),
        ),
        migrations.AlterField(
            model_name='document',
            name='files',
            field=models.ImageField(null=True, upload_to='otherdocs/'),
        ),
    ]
