# Generated by Django 2.2 on 2020-02-01 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrd', '0004_auto_20200201_1744'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankdetails',
            name='emp_id',
            field=models.IntegerField(null=True),
        ),
    ]
