# Generated by Django 2.2 on 2020-02-01 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrd', '0005_bankdetails_emp_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankdetails',
            name='ifsc_code',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
