# Generated by Django 2.2.6 on 2020-02-01 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrd', '0006_auto_20200201_1841'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='emp_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='document',
            name='document_status',
            field=models.CharField(choices=[('Provided', 'Provided'), ('Submitted', 'Submitted')], max_length=55, null=True),
        ),
    ]
